### ISSUE TITLE
Multiple GPUs

### ISSUE THREAD

**Issue by shaners91** [Mandelhoff/AmoveoMinerGpuCuda#2]
Hello All, 

Sorry for this noob question but i am running the gpu miner on my windows 10 machine with 2 Nvidia 1070 GPUs but only one seems to be working. Am i doing something wrong or does it currently only work with one GPU?

Thanks in advance,
Shaners91

**Comment by Mandelhoff** [comment]
Use the Device Id option and kick off two command prompt processes:
AmoveoMinerGpuCuda.exe {Base64AmoveoAddress} {CudaDeviceId}

Usually, DeviceId goes 0, 1, 2, 3... so you'd kick off two miner process with 0 and 1 like this in separate console windows:
AmoveoMinerGpuCuda.exe {Base64AmoveoAddress} 0
AmoveoMinerGpuCuda.exe {Base64AmoveoAddress} 1
