### ISSUE TITLE
CUDA Version

### ISSUE THREAD

**Issue by imedjendoubi** [Mandelhoff/AmoveoMinerGpuCuda#5]
"GPU: cudaError 35 (CUDA driver version is insufficient for CUDA runtime version)
ERROR: GetWork failed. Sleep and retry..."

How can i solve this issue ?

P106 Rig

**Comment by Mandelhoff** [comment]
It looks like you will need CUDA 9.1 installed. Perhaps you have an older CUDA version installed.

You may want to use the VeoMiner tool. I think it also requires CUDA 9.1, but it's much faster than AmoveoMinerGpuCuda. Here's the link:

https://github.com/PhamHuong92/VeoMiner
